{
 "title": "Ocellus Metrics",
 "tags": [ "ocellus" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "RAPL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RAPL Package Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ocellus_rapl_power_watts{domain=\"package\"}",
     "legendFormat": "pkg={{package}} die-group={{die_group}} die={{die}}"
    }
   ]
  },
  {
   "title": "RAPL DRAM Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ocellus_rapl_power_watts{domain=\"dram\"}",
     "legendFormat": "pkg={{package}} die-group={{die_group}} die={{die}}"
    }
   ]
  },
  { "title": "TSC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "TSC Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    { "expr": "ocellus_tsc_frequency_hz", "legendFormat": "TSC frequency" }
   ]
  }
 ]
}